version: '3.8'

services:
  mySQL:
    image: mysql:8.0.32
    restart: always
    container_name: mysqlDB
    environment:
      - MYSQL_DATABASE=db_springboot
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=sasa1234
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql