version: '3.8'

services:
  postgres-db:
    image: postgres:14.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo-ddd
      - POSTGRES_PASSWORD=sasa1234
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432