spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/db_products
        username: postgres
        password: sasa1234
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
  
