
server:
  port: ${PORT}

spring:
    config:
      import:
      - "optional:file:.env[.properties]"   
    application:
        name: accounts
    datasource:
        url: jdbc:postgresql://${DB_HOST}/${DB_DATABASE}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: update
