version: '3.8'

services:
  postgres-db:
    image: postgres:15.3
    restart: always
    container_name: account_spring_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=accountsdb
      - POSTGRES_PASSWORD=sasa1234
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
